#!/usr/bin/env node

/**
 * Shared test harness for the AIDLC Starter Kit test suite.
 *
 * Provides assertion helpers, file-scanning utilities, and a
 * section/summary renderer matching the BMAD-METHOD test style:
 *   - Custom assert helpers with colored pass/fail markers
 *   - Exit code 1 on any failure
 *   - Zero external dependencies (Node.js built-ins only)
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const VERBOSE = process.argv.includes('--verbose');

// ──────────────────────────────────────────────────────────────────────────
// Colors
// ──────────────────────────────────────────────────────────────────────────

const FG = {
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
  dim: '\x1b[2m',
  bold: '\x1b[1m',
  reset: '\x1b[0m',
};

// ──────────────────────────────────────────────────────────────────────────
// Counters — cumulative across all suites in a single process.
// Each suite file imports this module and increments the shared counters.
// printSummary() reports the grand total, not per-suite breakdowns.
// When suites run in separate processes (via test-all.js), each gets
// its own counter state, so the overall summary remains correct.
// ──────────────────────────────────────────────────────────────────────────

let totalTests = 0;
let passCount = 0;
let failCount = 0;
let skipCount = 0;
const failures = [];

// ──────────────────────────────────────────────────────────────────────────
// Assertion helpers
// ──────────────────────────────────────────────────────────────────────────

function pass(testId, message) {
  totalTests++;
  passCount++;
  if (VERBOSE) {
    console.log(`  ${FG.green}✓${FG.reset} ${FG.dim}[${testId}]${FG.reset} ${message}`);
  }
}

function fail(testId, message, details) {
  totalTests++;
  failCount++;
  console.log(`  ${FG.red}✗${FG.reset} ${FG.bold}[${testId}]${FG.reset} ${message}`);
  if (details) {
    const lines = Array.isArray(details) ? details : [details];
    for (const line of lines) {
      console.log(`    ${FG.dim}${line}${FG.reset}`);
    }
  }
  failures.push({ testId, message, details });
}

function skip(testId, message) {
  totalTests++;
  skipCount++;
  if (VERBOSE) {
    console.log(`  ${FG.yellow}○${FG.reset} ${FG.dim}[${testId}]${FG.reset} ${message} (skipped)`);
  }
}

function section(title) {
  console.log(`\n${FG.cyan}${FG.bold}── ${title} ──${FG.reset}`);
}

function assertEqual(testId, actual, expected, message) {
  if (actual === expected) {
    pass(testId, message || `${actual} === ${expected}`);
  } else {
    fail(testId, message || `Expected ${expected}, got ${actual}`, [`actual:   ${JSON.stringify(actual)}`, `expected: ${JSON.stringify(expected)}`]);
  }
}

function assertMatch(testId, value, pattern, message) {
  if (pattern.test(value)) {
    pass(testId, message || `Matches ${pattern}`);
  } else {
    fail(testId, message || `Does not match ${pattern}`, [`value: ${JSON.stringify(value).substring(0, 200)}`]);
  }
}

function assertTrue(testId, condition, message, details) {
  if (condition) {
    pass(testId, message);
  } else {
    fail(testId, message, details);
  }
}

// ──────────────────────────────────────────────────────────────────────────
// File scanning
// ──────────────────────────────────────────────────────────────────────────

// plan/ and adr/ are gitignored internal planning docs; CHANGELOG is auto-generated;
// review-report.md is a gitignored working doc generated by /i2a-manage-review.
// Excluding them avoids false positives from draft content and placeholder text.
const DEFAULT_EXCLUDE = [/\/plan\//, /\/adr\//, /CHANGELOG\.md$/, /node_modules/, /review-report\.md$/, /tdgs-aidlc-rom-estimate[\\/.]/, /\/rom-estimate\.tmpl\./];

function collectFiles(dirs, { extensions = ['.md', '.yml', '.yaml'], exclude = DEFAULT_EXCLUDE } = {}) {
  const files = [];
  function walk(dir) {
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      const relPath = path.relative(ROOT, fullPath);
      if (exclude.some((p) => p.test(relPath))) continue;
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (extensions.some((ext) => entry.name.endsWith(ext))) {
        files.push({ fullPath, relPath });
      }
    }
  }
  for (const dir of dirs) {
    walk(path.resolve(ROOT, dir));
  }
  return files;
}

function readContent(filePath) {
  // Normalize CRLF to LF for consistent regex matching
  return fs.readFileSync(filePath, 'utf8').replace(/\r\n/g, '\n');
}

/**
 * Search files for a regex. Returns { file, line, lineNum, match }[].
 */
function searchFiles(files, pattern) {
  const results = [];
  for (const { fullPath, relPath } of files) {
    const content = readContent(fullPath);
    const lines = content.split('\n');
    for (let i = 0; i < lines.length; i++) {
      const m = lines[i].match(pattern);
      if (m) {
        results.push({ file: relPath, line: lines[i].trim(), lineNum: i + 1, match: m[0] });
      }
    }
  }
  return results;
}

function formatHits(hits, max = 10) {
  const lines = hits.slice(0, max).map((h) => `${h.file}:${h.lineNum}: ${h.line.substring(0, 120)}`);
  if (hits.length > max) lines.push(`... and ${hits.length - max} more`);
  return lines;
}

// ──────────────────────────────────────────────────────────────────────────
// Summary
// ──────────────────────────────────────────────────────────────────────────

function printSummary(suiteLabel) {
  console.log(`\n${FG.bold}${'═'.repeat(60)}${FG.reset}`);
  console.log(`${FG.bold}${suiteLabel || 'Summary'}${FG.reset}`);
  console.log(`  Total:   ${totalTests}`);
  console.log(`  ${FG.green}Passed:  ${passCount}${FG.reset}`);
  if (failCount > 0) {
    console.log(`  ${FG.red}Failed:  ${failCount}${FG.reset}`);
  } else {
    console.log(`  Failed:  0`);
  }
  if (skipCount > 0) {
    console.log(`  ${FG.yellow}Skipped: ${skipCount}${FG.reset}`);
  }
  if (failCount > 0) {
    console.log(`\n${FG.red}${FG.bold}FAIL${FG.reset} — ${failCount} test(s) failed.\n`);
  } else {
    console.log(`\n${FG.green}${FG.bold}PASS${FG.reset} — All ${passCount} checks passed.\n`);
  }
  return failCount;
}

// ──────────────────────────────────────────────────────────────────────────
// Exports
// ──────────────────────────────────────────────────────────────────────────

module.exports = {
  ROOT,
  VERBOSE,
  FG,
  pass,
  fail,
  skip,
  section,
  assertEqual,
  assertMatch,
  assertTrue,
  collectFiles,
  readContent,
  searchFiles,
  formatHits,
  printSummary,
  get totalTests() { return totalTests; },
  get passCount() { return passCount; },
  get failCount() { return failCount; },
  get skipCount() { return skipCount; },
  get failures() { return failures; },
};
